trigger:
- none

jobs:
- template: conda-build.yml
  parameters:
    name: Linux_freeimageplus
    vmImage: 'ubuntu-16.04'
    py_maj: 3
    py_min: 6
    location: freeimageplus

- template:  conda-build.yml
  parameters:
    name: macOS_freeimageplus
    vmImage: 'macOS-10.13'
    py_maj: 3
    py_min: 6
    location: freeimageplus

- template:  conda-build.yml
  parameters:
    name: Windows_freeimageplus
    vmImage: 'vs2017-win2016'
    py_maj: 3
    py_min: 6
    location: freeimageplus
    conda_bld: 3.18
    
- template: conda-build.yml
  parameters:
    name: Linux_oce
    vmImage: 'ubuntu-16.04'
    py_maj: 3
    py_min: 6
    location: oce-0.18.3

- template:  conda-build.yml
  parameters:
    name: macOS_oce
    vmImage: 'macOS-10.13'
    py_maj: 3
    py_min: 6
    location: oce-0.18.3

- template:  conda-build.yml
  parameters:
    name: Windows_oce
    vmImage: 'vs2017-win2016'
    py_maj: 3
    py_min: 6
    location: oce-0.18.3
    conda_bld: 3.17

- template: conda-build.yml
  parameters:
    name: Linux_pythonocc36
    vmImage: 'ubuntu-16.04'
    py_maj: 3
    py_min: 6
    location: pythonocc

- template:  conda-build.yml
  parameters:
    name: macOS_pythonocc36
    vmImage: 'macOS-10.13'
    py_maj: 3
    py_min: 6
    location: pythonocc

- template:  conda-build.yml
  parameters:
    name: Windows_pythonocc36
    vmImage: 'vs2017-win2016'
    py_maj: 3
    py_min: 6
    location: pythonocc
    conda_bld: 3.17

- template: conda-build.yml
  parameters:
    name: Linux_pythonocc37
    vmImage: 'ubuntu-16.04'
    py_maj: 3
    py_min: 7
    location: pythonocc

- template:  conda-build.yml
  parameters:
    name: macOS_pythonocc37
    vmImage: 'macOS-10.13'
    py_maj: 3
    py_min: 7
    location: pythonocc

- template:  conda-build.yml
  parameters:
    name: Windows_pythonocc37
    vmImage: 'vs2017-win2016'
    py_maj: 3
    py_min: 7
    location: pythonocc
    conda_bld: 3.17
